import type { Metadata } from "next";
import { Audiowide, Titillium_Web } from "next/font/google";
import { Suspense } from "react";
import { Navbar } from "@/components/global/Navbar";
import { NavbarWrapper } from "@/components/global/NavbarWrapper";
import { Footer } from "@/components/global/Footer";
import "./globals.css";

const audiowide = Audiowide({
  weight: "400",
  variable: "--font-audiowide",
  subsets: ["latin"],
  display: "swap",
});

const titilliumWeb = Titillium_Web({
  weight: ["200", "300", "400", "600", "700"],
  variable: "--font-titillium",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${audiowide.variable} ${titilliumWeb.variable} antialiased`}
        suppressHydrationWarning
      >
        <Suspense fallback={<Navbar />}>
          <NavbarWrapper />
        </Suspense>
        <main className="min-h-screen pt-0">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
